#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Thu Mar 12 16:36:18 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1584002178505
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1584002177400
maven-metadata-jcenter.xml.lastUpdated=1584002177860
maven-metadata-jitpack.io.xml.error=
