#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue Sep 01 10:21:57 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-snapshots.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1598926917786
maven-metadata-snapshots.xml.lastUpdated=1598926916690
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1598926916526
maven-metadata-jcenter.xml.lastUpdated=1598926917059
maven-metadata-jitpack.io.xml.error=
