#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue Jan 07 11:11:14 CST 2020
maven-metadata-JBossPublic.xml.lastUpdated=1572676748444
maven-metadata-spigot-repo.xml.error=
maven-metadata-bungeecord-repo.xml.error=
maven-metadata-JBossPublic.xml.error=
maven-metadata-dropbox-mvn-repo.xml.lastUpdated=1571550879830
maven-metadata-spigot-repo.xml.lastUpdated=1573817194591
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1578366674838
maven-metadata-bungeecord-repo.xml.lastUpdated=1573829596386
maven-metadata-dropbox-mvn-repo.xml.error=
maven-metadata-jcenter.xml.lastUpdated=1578366672755
maven-metadata-jitpack.io.xml.error=
