#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Fri Mar 06 10:27:04 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1583461624372
maven-metadata-jcenter.xml.lastUpdated=1573912818038
