#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 10:19:20 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1583806760367
maven-metadata-jcenter.xml.lastUpdated=1583638073339
