#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Wed Feb 19 08:51:29 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1582073489087
maven-metadata-jcenter.xml.lastUpdated=1573912818038
