#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 10:19:19 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1583806758957
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1583806759029
maven-metadata-dropbox-mvn-repo.xml.error=
maven-metadata-dropbox-mvn-repo.xml.lastUpdated=1578381748613
maven-metadata-jcenter.xml.lastUpdated=1583806759473
maven-metadata-jitpack.io.xml.error=
