#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue Jan 07 11:11:18 CST 2020
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1578366678720
maven-metadata-JBossPublic.xml.lastUpdated=1572676749363
maven-metadata-dropbox-mvn-repo.xml.error=
maven-metadata-dropbox-mvn-repo.xml.lastUpdated=1571550883006
maven-metadata-JBossPublic.xml.error=
maven-metadata-jcenter.xml.lastUpdated=1578366676233
maven-metadata-jitpack.io.xml.error=
