#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Thu Feb 27 00:26:59 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-jcenter.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1582734419761
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1582168239440
maven-metadata-dropbox-mvn-repo.xml.error=
maven-metadata-dropbox-mvn-repo.xml.lastUpdated=1578381748613
maven-metadata-jcenter.xml.lastUpdated=1582734419176
maven-metadata-jitpack.io.xml.error=
