#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Thu Mar 12 16:36:15 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1584002175922
