#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Thu Feb 20 11:10:37 CST 2020
maven-metadata-ultra-mvn-repo.xml.error=
maven-metadata-ultra-mvn-repo.xml.lastUpdated=1582168237073
maven-metadata-dropbox-mvn-repo.xml.error=
maven-metadata-dropbox-mvn-repo.xml.lastUpdated=1571550883968
